apiVersion: v1
kind: Service
metadata:
  name: {{ include "omyxia.fullname" . }}-api
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: 80
      targetPort: 3001
  selector:
    app: omyxia-api
