apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "omyxia.fullname" . }}-api
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: omyxia-api
  template:
    metadata:
      labels:
        app: omyxia-api
    spec:
      containers:
        - name: api
          image: "{{ .Values.image.repository }}-api:{{ .Values.image.tag }}"
          ports:
            - containerPort: 3001
          envFrom:
            - configMapRef:
                name: {{ include "omyxia.fullname" . }}-config
          resources:
            {{- toYaml .Values.resources.api | nindent 12 }}
