apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "omyxia.fullname" . }}-web
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: omyxia-web
  template:
    metadata:
      labels:
        app: omyxia-web
    spec:
      containers:
        - name: web
          image: "{{ .Values.image.repository }}-web:{{ .Values.image.tag }}"
          ports:
            - containerPort: 3000
          resources:
            {{- toYaml .Values.resources.web | nindent 12 }}
